# linear regression
## spring
[link](https://docs.google.com/presentation/d/1L1LwpKm5DxhHndiyyiZ3wJA2mKOJTQ2heKo45Me5yVg/edit#slide=id.g1eaee6a347_0_8)

## fall
[link](https://ntumlta.github.io/2017fall-ml-hw1/)

- hw1.sh
 - Python3.5+ required
 - Only (1)numpy (2)scipy (3)pandas are allowed
 - numpy.linalg.lstsq is forbidden.
 - Please handcraft "linear regression" using Gradient Descent
 - beat public simple baseline
 - For those who wish to load model instead of running whole training precess:
 - please upload your training code named train.py
 - as long as there are Gradient Descent Code in train.py, it's fine
- hw1_best.sh
 - Python3.5+ required
 - any library is allowed
 - meet the higher score you choose in kaggle
 
 ### Data 簡介

* [train.csv](./data/train.csv) : 每個月前20天每個小時的氣象資料(每小時有18種測資)。共12個月。
* [test.csv](./data/test.csv) : 排除train.csv中剩餘的資料，取連續9小時的資料當feature，預測第10小時的PM2.5值。總共取240筆不重複的test data。
* [sampleSubmission.csv](./data/sampleSubmission.csv)
* [testing答案](./data/ans.csv)

## linear regression

找出 $f$ 使得  
loss function() $$L(f) = \sum_{f} (\hat{y}^n - f(x))^2$$ 最小 $f^* = arg \displaystyle \min_{f} L(f)$  
又因為 $f(X) = b + w \cdot X$, where $X \in \Omega, b \in \Bbb{F}$
可以寫成 $$L(b, w) = \sum_{b, w} (\hat{y}^n - b - w \cdot X)^2$$
引此可以將題目變成找
$$b^*, w^* = arg \min_{b,w} \sum_{b, w} (\hat{y}^n - b - w \cdot X)^2$$

In [177]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

train = "./data/train.csv"
test = "./data/test.csv"

df = pd.read_csv(train, parse_dates={'date':[0]}, encoding='big5')
test_df = pd.read_csv(test, encoding='big5', header=None)

In [178]:
df.shape

(4320, 27)

In [179]:
df.head(18) #測項有18項

,date,測站,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014-01-01,豐原,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014-01-01,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014-01-01,豐原,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014-01-01,豐原,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014-01-01,豐原,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,2014-01-01,豐原,NO2,16,9.2,8.2,6.9,6.8,3.8,6.9,...,11,11,22,28,19,12,8.1,7,6.9,6
6,2014-01-01,豐原,NOx,17,9.8,8.7,8.6,8.5,5.3,8.8,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,2014-01-01,豐原,O3,16,30,27,23,24,28,24,...,65,64,51,34,33,34,37,38,38,36
8,2014-01-01,豐原,PM10,56,50,48,35,25,12,4,...,52,51,66,85,85,63,46,36,42,42
9,2014-01-01,豐原,PM2.5,26,39,36,35,31,28,25,...,36,45,42,49,45,44,41,30,24,13
10,2014-01-01,豐原,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR
11,2014-01-01,豐原,RH,77,68,67,74,72,73,74,...,47,49,56,67,72,69,70,70,70,69
12,2014-01-01,豐原,SO2,1.8,2,1.7,1.6,1.9,1.4,1.5,...,3.9,4.4,9.9,5.1,3.4,2.3,2,1.9,1.9,1.9
13,2014-01-01,豐原,THC,2,2,2,1.9,1.9,1.8,1.9,...,1.9,1.9,1.9,2.1,2,1.9,1.9,1.9,1.9,1.9
14,2014-01-01,豐原,WD_HR,37,80,57,76,110,106,101,...,307,304,307,124,118,121,113,112,106,110
15,2014-01-01,豐原,WIND_DIREC,35,79,2.4,55,94,116,106,...,313,305,291,124,119,118,114,108,102,111
16,2014-01-01,豐原,WIND_SPEED,1.4,1.8,1,0.6,1.7,2.5,2.5,...,2.5,2.2,1.4,2.2,2.8,3,2.6,2.7,2.1,2.1
17,2014-01-01,豐原,WS_HR,0.5,0.9,0.6,0.3,0.6,1.9,2,...,2.1,2.1,1.9,1,2.5,2.5,2.8,2.6,2.4,2.3

In [180]:
def rainfall(raindata):
    try:
        return float(raindata)
    except:
        return 0

In [181]:
grouped = df.groupby("測項")
# rainfall is label data
df.iloc[grouped.groups.get("RAINFALL"),3:] = \
            df.iloc[grouped.groups.get("RAINFALL"),3:].applymap(rainfall)
# change data types
df.iloc[:,3:] = df.iloc[:,3:].astype(np.float16)

In [182]:
df.head(18)

,date,測站,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014-01-01,豐原,AMB_TEMP,14.000000,14.000000,14.000000,13.000000,12.000000,12.000000,12.000000,...,22.000000,22.000000,21.000000,19.000000,17.000000,16.000000,15.000000,15.000000,15.000000,15.000000
1,2014-01-01,豐原,CH4,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,...,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805,1.799805
2,2014-01-01,豐原,CO,0.509766,0.409912,0.389893,0.370117,0.350098,0.300049,0.370117,...,0.370117,0.370117,0.469971,0.689941,0.560059,0.449951,0.379883,0.350098,0.360107,0.320068
3,2014-01-01,豐原,NMHC,0.199951,0.150024,0.130005,0.119995,0.109985,0.059998,0.099976,...,0.099976,0.130005,0.140015,0.229980,0.180054,0.119995,0.099976,0.090027,0.099976,0.080017
4,2014-01-01,豐原,NO,0.899902,0.600098,0.500000,1.700195,1.799805,1.500000,1.900391,...,2.500000,2.199219,2.500000,2.300781,2.099609,1.900391,1.500000,1.599609,1.799805,1.500000
5,2014-01-01,豐原,NO2,16.000000,9.203125,8.203125,6.898438,6.800781,3.800781,6.898438,...,11.000000,11.000000,22.000000,28.000000,19.000000,12.000000,8.101562,7.000000,6.898438,6.000000
6,2014-01-01,豐原,NOx,17.000000,9.796875,8.703125,8.601562,8.500000,5.300781,8.796875,...,14.000000,13.000000,25.000000,30.000000,21.000000,13.000000,9.703125,8.601562,8.703125,7.500000
7,2014-01-01,豐原,O3,16.000000,30.000000,27.000000,23.000000,24.000000,28.000000,24.000000,...,65.000000,64.000000,51.000000,34.000000,33.000000,34.000000,37.000000,38.000000,38.000000,36.000000
8,2014-01-01,豐原,PM10,56.000000,50.000000,48.000000,35.000000,25.000000,12.000000,4.000000,...,52.000000,51.000000,66.000000,85.000000,85.000000,63.000000,46.000000,36.000000,42.000000,42.000000
9,2014-01-01,豐原,PM2.5,26.000000,39.000000,36.000000,35.000000,31.000000,28.000000,25.000000,...,36.000000,45.000000,42.000000,49.000000,45.000000,44.000000,41.000000,30.000000,24.000000,13.000000
10,2014-01-01,豐原,RAINFALL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2014-01-01,豐原,RH,77.000000,68.000000,67.000000,74.000000,72.000000,73.000000,74.000000,...,47.000000,49.000000,56.000000,67.000000,72.000000,69.000000,70.000000,70.000000,70.000000,69.000000
12,2014-01-01,豐原,SO2,1.799805,2.000000,1.700195,1.599609,1.900391,1.400391,1.500000,...,3.900391,4.398438,9.898438,5.101562,3.400391,2.300781,2.000000,1.900391,1.900391,1.900391
13,2014-01-01,豐原,THC,2.000000,2.000000,2.000000,1.900391,1.900391,1.799805,1.900391,...,1.900391,1.900391,1.900391,2.099609,2.000000,1.900391,1.900391,1.900391,1.900391,1.900391
14,2014-01-01,豐原,WD_HR,37.000000,80.000000,57.000000,76.000000,110.000000,106.000000,101.000000,...,307.000000,304.000000,307.000000,124.000000,118.000000,121.000000,113.000000,112.000000,106.000000,110.000000
15,2014-01-01,豐原,WIND_DIREC,35.000000,79.000000,2.400391,55.000000,94.000000,116.000000,106.000000,...,313.000000,305.000000,291.000000,124.000000,119.000000,118.000000,114.000000,108.000000,102.000000,111.000000
16,2014-01-01,豐原,WIND_SPEED,1.400391,1.799805,1.000000,0.600098,1.700195,2.500000,2.500000,...,2.500000,2.199219,1.400391,2.199219,2.800781,3.000000,2.599609,2.699219,2.099609,2.099609
17,2014-01-01,豐原,WS_HR,0.500000,0.899902,0.600098,0.300049,0.600098,1.900391,2.000000,...,2.099609,2.099609,1.900391,1.000000,2.500000,2.500000,2.800781,2.599609,2.400391,2.300781

In [101]:
# normalize
# for key, index in grouped.groups.items():
#     item_values = grouped.get_group(key).iloc[:,3:].values.flatten()
#     item_avg = item_values.mean()
#     item_std = item_values.std()
#     df.iloc[index,3:] = df.iloc[index,3:]-item_avg
#     df.iloc[index,3:] = df.iloc[index,3:]/item_std
#     print(key, item_avg, item_std)

AMB_TEMP 22.5274131944 6.28960619484
CH4 1.70239583333 0.125254558508
CO 0.388362847222 0.323544567397
NMHC 0.140427083333 0.104635735025
NO 2.13572916667 2.2819569657
NO2 10.1259895833 6.18701792958
NOx 12.2477256944 7.57647572496
O3 31.90546875 18.7018620848
PM10 42.7092013889 26.2200156539
PM2.5 21.4142361111 16.661090904
RAINFALL 0.200625 2.0452654401
RH 73.2291666667 13.3601910488
SO2 2.763125 1.81678266784
THC 1.83965277778 0.181822995407
WD_HR 156.329270833 95.7375696937
WIND_DIREC 158.482795139 94.6892111736
WIND_SPEED 2.29723958333 1.06531539649
WS_HR 1.71276041667 1.06259085472

In [183]:
grouped_bydate = df.groupby('date')

In [184]:
# 取連續9小時的資料當feature，預測第10小時的PM2.5
X_train = []
y_train = []
for date, index in grouped_bydate.groups.items():
    print(date)
    X_train.append(grouped_bydate.get_group(date).iloc[:,3:12].values.flatten())
    y_train.append(grouped_bydate.get_group(date).iloc[9,13])

2014-01-01 00:00:00
2014-01-02 00:00:00
2014-01-03 00:00:00
2014-01-04 00:00:00
2014-01-05 00:00:00
2014-01-06 00:00:00
2014-01-07 00:00:00
2014-01-08 00:00:00
2014-01-09 00:00:00
2014-01-10 00:00:00
2014-01-11 00:00:00
2014-01-12 00:00:00
2014-01-13 00:00:00
2014-01-14 00:00:00
2014-01-15 00:00:00
2014-01-16 00:00:00
2014-01-17 00:00:00
2014-01-18 00:00:00
2014-01-19 00:00:00
2014-01-20 00:00:00
2014-02-01 00:00:00
2014-02-02 00:00:00
2014-02-03 00:00:00
2014-02-04 00:00:00
2014-02-05 00:00:00
2014-02-06 00:00:00
2014-02-07 00:00:00
2014-02-08 00:00:00
2014-02-09 00:00:00
2014-02-10 00:00:00
2014-02-11 00:00:00
2014-02-12 00:00:00
2014-02-13 00:00:00
2014-02-14 00:00:00
2014-02-15 00:00:00
2014-02-16 00:00:00
2014-02-17 00:00:00
2014-02-18 00:00:00
2014-02-19 00:00:00
2014-02-20 00:00:00
2014-03-01 00:00:00
2014-03-02 00:00:00
2014-03-03 00:00:00
2014-03-04 00:00:00
2014-03-05 00:00:00
2014-03-06 00:00:00
2014-03-07 00:00:00
2014-03-08 00:00:00
2014-03-09 00:00:00
2014-03-10 00:00:00
2014-03-11 00:00:00
2014-03-12 00:00:00
2014-03-13 00:00:00
2014-03-14 00:00:00
2014-03-15 00:00:00
2014-03-16 00:00:00
2014-03-17 00:00:00
2014-03-18 00:00:00
2014-03-19 00:00:00
2014-03-20 00:00:00
2014-04-01 00:00:00
2014-04-02 00:00:00
2014-04-03 00:00:00
2014-04-04 00:00:00
2014-04-05 00:00:00
2014-04-06 00:00:00
2014-04-07 00:00:00
2014-04-08 00:00:00
2014-04-09 00:00:00
2014-04-10 00:00:00
2014-04-11 00:00:00
2014-04-12 00:00:00
2014-04-13 00:00:00
2014-04-14 00:00:00
2014-04-15 00:00:00
2014-04-16 00:00:00
2014-04-17 00:00:00
2014-04-18 00:00:00
2014-04-19 00:00:00
2014-04-20 00:00:00
2014-05-01 00:00:00
2014-05-02 00:00:00
2014-05-03 00:00:00
2014-05-04 00:00:00
2014-05-05 00:00:00
2014-05-06 00:00:00
2014-05-07 00:00:00
2014-05-08 00:00:00
2014-05-09 00:00:00
2014-05-10 00:00:00
2014-05-11 00:00:00
2014-05-12 00:00:00
2014-05-13 00:00:00
2014-05-14 00:00:00
2014-05-15 00:00:00
2014-05-16 00:00:00
2014-05-17 00:00:00
2014-05-18 00:00:00
2014-05-19 00:00:00
2014-05-20 00:00:00
2014-06-01 00:00:00
2014-06-02 00:00:00
2014-06-03 00:00:00
2014-06-04 00:00:00
2014-06-05 00:00:00
2014-06-06 00:00:00
2014-06-07 00:00:00
2014-06-08 00:00:00
2014-06-09 00:00:00
2014-06-10 00:00:00
2014-06-11 00:00:00
2014-06-12 00:00:00
2014-06-13 00:00:00
2014-06-14 00:00:00
2014-06-15 00:00:00
2014-06-16 00:00:00
2014-06-17 00:00:00
2014-06-18 00:00:00
2014-06-19 00:00:00
2014-06-20 00:00:00
2014-07-01 00:00:00
2014-07-02 00:00:00
2014-07-03 00:00:00
2014-07-04 00:00:00
2014-07-05 00:00:00
2014-07-06 00:00:00
2014-07-07 00:00:00
2014-07-08 00:00:00
2014-07-09 00:00:00
2014-07-10 00:00:00
2014-07-11 00:00:00
2014-07-12 00:00:00
2014-07-13 00:00:00
2014-07-14 00:00:00
2014-07-15 00:00:00
2014-07-16 00:00:00
2014-07-17 00:00:00
2014-07-18 00:00:00
2014-07-19 00:00:00
2014-07-20 00:00:00
2014-08-01 00:00:00
2014-08-02 00:00:00
2014-08-03 00:00:00
2014-08-04 00:00:00
2014-08-05 00:00:00
2014-08-06 00:00:00
2014-08-07 00:00:00
2014-08-08 00:00:00
2014-08-09 00:00:00
2014-08-10 00:00:00
2014-08-11 00:00:00
2014-08-12 00:00:00
2014-08-13 00:00:00
2014-08-14 00:00:00
2014-08-15 00:00:00
2014-08-16 00:00:00
2014-08-17 00:00:00
2014-08-18 00:00:00
2014-08-19 00:00:00
2014-08-20 00:00:00
2014-09-01 00:00:00
2014-09-02 00:00:00
2014-09-03 00:00:00
2014-09-04 00:00:00
2014-09-05 00:00:00
2014-09-06 00:00:00
2014-09-07 00:00:00
2014-09-08 00:00:00
2014-09-09 00:00:00
2014-09-10 00:00:00
2014-09-11 00:00:00
2014-09-12 00:00:00
2014-09-13 00:00:00
2014-09-14 00:00:00
2014-09-15 00:00:00
2014-09-16 00:00:00
2014-09-17 00:00:00
2014-09-18 00:00:00
2014-09-19 00:00:00
2014-09-20 00:00:00
2014-10-01 00:00:00
2014-10-02 00:00:00
2014-10-03 00:00:00
2014-10-04 00:00:00
2014-10-05 00:00:00
2014-10-06 00:00:00
2014-10-07 00:00:00
2014-10-08 00:00:00
2014-10-09 00:00:00
2014-10-10 00:00:00
2014-10-11 00:00:00
2014-10-12 00:00:00
2014-10-13 00:00:00
2014-10-14 00:00:00
2014-10-15 00:00:00
2014-10-16 00:00:00
2014-10-17 00:00:00
2014-10-18 00:00:00
2014-10-19 00:00:00
2014-10-20 00:00:00
2014-11-01 00:00:00
2014-11-02 00:00:00
2014-11-03 00:00:00
2014-11-04 00:00:00
2014-11-05 00:00:00
2014-11-06 00:00:00
2014-11-07 00:00:00
2014-11-08 00:00:00
2014-11-09 00:00:00
2014-11-10 00:00:00
2014-11-11 00:00:00
2014-11-12 00:00:00
2014-11-13 00:00:00
2014-11-14 00:00:00
2014-11-15 00:00:00
2014-11-16 00:00:00
2014-11-17 00:00:00
2014-11-18 00:00:00
2014-11-19 00:00:00
2014-11-20 00:00:00
2014-12-01 00:00:00
2014-12-02 00:00:00
2014-12-03 00:00:00
2014-12-04 00:00:00
2014-12-05 00:00:00
2014-12-06 00:00:00
2014-12-07 00:00:00
2014-12-08 00:00:00
2014-12-09 00:00:00
2014-12-10 00:00:00
2014-12-11 00:00:00
2014-12-12 00:00:00
2014-12-13 00:00:00
2014-12-14 00:00:00
2014-12-15 00:00:00
2014-12-16 00:00:00
2014-12-17 00:00:00
2014-12-18 00:00:00
2014-12-19 00:00:00
2014-12-20 00:00:00

In [185]:
type(X_train[0])

numpy.ndarray

In [186]:
test = np.matrix(X_train)

In [187]:
test_std = (test-test.mean(axis=0))/test.std(0)

In [197]:
class standardize():
    mean = None
    std = None
    def __init__(self):
        pass
    def fit(self, X):
        '''X as matrix like'''
        X = np.matrix(X)
        self.mean = X.mean(0)
        self.std = X.std(0)
    def transfer(self, X):
        try:
            return (X-self.mean)/self.std
        except:
            print("dimesion may be same of fitting")

## gradient descent
$x_{n+1} = x_n - \eta_n\nabla{f(x_n)} $ s.t. $f(x_{n+1})\le f(x_n))$
現在 $f = L(W,b) = \displaystyle\sum_{X} (\hat{y} - b - W \cdot X)^2$因此
$$\begin{aligned}
\nabla L(w,b) &= 
    \begin{bmatrix}
    {\partial L(w_1,b)}\over{\partial w}  \\
    \vdots \\
    {\partial L(w,b)}\over{\partial b}
    \end{bmatrix}\\
 &=
    \begin{bmatrix}
     \sum_{X} -2 x_i (\hat{y} -b - W \cdot X) \\
     \vdots \\
     \sum_{X} -2 (\hat{y} - b - W\cdot X)
    \end{bmatrix}\\
\end{aligned}
$$

In [135]:
# 
def loss_func( b, W, X=X_train, y=y_train):
    sum = 0
    w = np.array(W)
    for idx in range(len(y)):
        sum = sum + ( y[idx] - b - np.dot(w, X[idx]))**2
    return sum

In [136]:
X_train[0].size

162

In [137]:
W = np.zeros(163)

loss_func(W[0],W[1:])

173399.0

In [138]:
def grad( b, W, X=X_train, y=y_train):
    """
    input b scale, W array_like
    ouput grad L(b,W)
    """
    card_datas = len(y)
    #b_array = np.full(card_datas, b)
    W = np.array(W)
    #X = np.ndarray(X)
    #y = np.array(y)
    feature_length = len(W)
    b_sum = 0
    w_sum = np.zeros(feature_length)
    for idx in range(card_datas):
        err = (y[idx] - b - np.dot(W, X[idx]))
        b_sum = b_sum - 2*err
        w_sum = w_sum - 2*err*X[idx]
    return (b_sum, w_sum)

In [139]:
b = 0
W = np.zeros(162)
eta = 0.00001
loss_0 = loss_func(b,W)
loss_1 = loss_0 + 1 
for i in range(20):
    gb, gW = grad(b,W)
    b = b - eta*gb
    W = W - eta*gW
    print(loss_func(b,W))

408176710717.0
1.58446311228e+18
6.15129494815e+24
2.38809168838e+31
9.27118917312e+37
3.59931526507e+44
1.39734721571e+51
5.42486305715e+57
2.10607205267e+64
8.176316055e+70
3.17425722195e+77
1.23232869709e+84
4.78421851632e+90
1.85735728348e+97
7.21074103688e+103
2.79939604315e+110
1.08679789862e+117
4.219230342e+123
1.63801427123e+130
6.35919477075e+136

In [143]:
b = 0
W = np.zeros(162)
eta = 0.00001
loss_0 = loss_func(b,W)
loss_1 = loss_0 -1 
count = 0
while True:
    tmp_err = loss_0 - loss_1 #error test avoid the loop too long
    gb, gW = grad(b,W)
    b = b - eta*gb
    W = W - eta*gW
    loss_0 = loss_1
    loss_1 = loss_func(b,W)
    count += 1
    if abs(tmp_err - loss_0 + loss_1) < 1e-6 or count > 5000:
        break
print(loss_0, loss_1)

C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in double_scalars

C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: overflow encountered in double_scalars
  from ipykernel import kernelapp as app
C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app
C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars

C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in subtract
C:\Users\Marshall\AppData\Local\conda\conda\envs\ML\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in multiply

nan nan

In [142]:
count

1

In [20]:
def haty(b, W, X):
    return b + np.dot(W,X)

In [21]:
test_df.head()

     0         1     2     3     4     5     6     7     8     9     10
0  id_0  AMB_TEMP    15    14    14    13    13    13    13    13    12
1  id_0       CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
2  id_0        CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
3  id_0      NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
4  id_0        NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9

In [117]:
def rainfall(raindata):
    '''rain data is object'''
    try:
        return float(raindata)
    except:
        return 0
    
def data_trans(df, item_index = 2, date_index = 0):
    '''transfer csv file to X,y forms with normalize
    here supports partitiion of datas is connected.
    train data item:2 date:0
    test data item:1 date:0'''
    data_start = item_index + 1
    data_end = data_start + 9 #
    columns = df.columns
    grouped_byitems = df.groupby(columns[item_index])
    grouped_bydate = df.groupby(columns[date_index])
    #trans object data to value
    df.iloc[grouped_byitems.groups.get("RAINFALL"), data_start:] = \
        df.iloc[grouped_byitems.groups.get("RAINFALL"), data_start:].\
        applymap(rainfall)
    # change data types
    df.iloc[:, data_start:] = df.iloc[:, data_start:].astype(float)
    #
    X_train = []
    y_train = []
    if data_end == 12:
        for date, index in grouped_bydate.groups.items():
            X_train.append(grouped_bydate.get_group(date).\
                           iloc[:,data_start:data_end].values.flatten())
            y_train.append(grouped_bydate.get_group(date).iloc[9,13])
    else:
        for date, index in grouped_bydate.groups.items():
            X_train.append(grouped_bydate.get_group(date).\
                           iloc[:,data_start:data_end].values.flatten())
    return  (X_train, y_train)

In [118]:
X, y = data_trans(df)

In [119]:
tX, ty = data_trans(test_df, item_index=1)

In [123]:
tX[0].size

162